spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

lianpayhub:
  security:
    api-auth-enabled: true
    api-auth-mode: signature
    sms-code-required: true
    sms-debug-return-code: false
    sms-provider: aliyun
  payment:
    dev-tools-enabled: false
    order-auto-close-enabled: true
